version: '3'

services:
   db:
    image: mysql:8.0-debian
    container_name: mysql_db
    tty: true
    environment:
      - MYSQL_DATABASE=moneymanager
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3063:3063
